Traceback (most recent call last):
  File "/Users/mihailgorbunov/dla/as/dla2023_as/train.py", line 111, in <module>
    main(config)
  File "/Users/mihailgorbunov/dla/as/dla2023_as/train.py", line 56, in main
    trainer = Trainer(
  File "/Users/mihailgorbunov/dla/as/dla2023_as/src/trainer/trainer.py", line 55, in __init__
    *[m.name for m in self.metrics], writer=self.writer
  File "/Users/mihailgorbunov/dla/as/dla2023_as/src/trainer/trainer.py", line 55, in <listcomp>
    *[m.name for m in self.metrics], writer=self.writer
  File "/Users/mihailgorbunov/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'EERMetric' object has no attribute 'name'